# Generated by Django 2.2.10 on 2020-02-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summmary',
            new_name='summary',
        ),
    ]
